### ISSUE TITLE
Invalid code behind #if false

### ISSUE THREAD

**Issue by Gama11** [Simn/hxparser#4]
https://github.com/HaxeFoundation/format/blob/master/format/tools/CRC32.hx#L35

Missing semicolon in line 35, which I guess worked in Haxe 2? The entire file is wrapped in `#if !haxe3` which is probably why it worked so far, so not sure if this one counts either.

```haxe
static inline function POLYNOM() return Int32.make(0xEDB8, 0x8320)
```

**Comment by Gama11** [comment]
Another one like these in Heaps' `Shadow.hx`:

![](http://i.imgur.com/1VizQ4S.png)

Something that's not even Haxe code from the looks of it, but never parsed because of `#if false`..

**Comment by Gama11** [comment]
More of this in [Starling](https://github.com/openfl/starling/blob/v1.8/samples/demo/src/Game.hx):

![](http://i.imgur.com/dy7mG0v.png)

**Comment by Simn** [comment]
I can't do anything about these, it's simply not valid Haxe code. I actually came across the first two as well, which is why I added the ignore.txt feature to ignore them.

**Comment by Gama11** [comment]
So these would fail to compile in Haxe 4 if the new parser is adopted?

**Comment by Simn** [comment]
Only if the branch is entered. Currently the parser just always goes for the `#if` branch because it doesn't evaluate any conditions.

**Comment by Gama11** [comment]
I guess I can close this then.
